### PR TITLE
update Platform File_Centric Mapping

### PR DESCRIPTION
**Pull request by ciaranschutte**
@blabadi what is the significance of ` "copy_to": ["file_autocomplete"]`?
Should this is not present in fields by default and we add it on a case by case basis?

### CODE REVIEW

**Comment by blabadi** [comment]
> @blabadi what is the significance of ` "copy_to": ["file_autocomplete"]`?
> Should this is not present in fields by default and we add it on a case by case basis?

I'd say so for now, I don't think there is a value of it on a lot of clinical fields.
this field "file_autocomplete" is used by the text field facet in the file repository to search through data and it's analyzed by ES for auto complete search style.. so it should only be used on fields that can narrow down user search when it's used.

**Comment by ciaranschutte** [comment]
removed autocomplete field for newly added fields other than ids

**Comment by ciaranschutte** [comment]
@rosibaj @hlminh2000 Can you two take a look at this please? It's a while since I touched it and wasn't sure about it then. I feel like there are probably changes to be do because this is very stale.

**Comment by ciaranschutte** [comment]
closing this because it's stale. sound ok @rosibaj ?

**Pull request closed without merging**
