### PR TITLE
Add rna seq

### PR DESCRIPTION
**Pull request by lindaxiang**

### CODE REVIEW

**Comment by junjun-zhang** [comment]
@lindaxiang, as discussed on Slack, regarding the new `analysisType`: `splice_junctions` and `supplement`, we need to think a bit more how to move forward in a constant way for future new analysis. On one hand, more specific types give better tracking and easier retrieval of metadata to enable workflow exectuion automation; one the other hand, more granular type leads to a lot of duplicated schemas, which can be hard to maintain (particularly manually).

If we take the fine grain analysisType approach (which we attempted at early stage), we need to come up with an easy way to update/maintain those analysis type specific schemas. It's possible to develop a tool to generate the schemas programmatically from reusable schema components.

**Comment by junjun-zhang** [comment]
On a different note, name of the `library_stranded` property can be better as `library_strandedness`?

As for the permissible values of `library_strandedness`, `First_Stranded` and `Second_Stranded` are unclear and possibly misleading. When the library is stranded, we need to know first read comes from which strand or which read (of the pair) represents the transcription strand.

See https://rnabio.org/module-09-appendix/0009/12/01/StrandSettings, https://salmon.readthedocs.io/en/latest/library_type.html#fragment-library-types and https://littlebitofdata.com/en/2017/08/strandness_in_rnaseq for more information.

Unfortunately, there seems no standard for how to express library strandedness. Although Salmon documentation illustrates most comprehensive way to express strandedness, but in practice many tools use much simplier notations. Personally, I find what Picard uses is most clear and unambiguous (if I understand it properly): `FIRST_READ_TRANSCRIPTION_STRAND` (stranded, first read strand is the transcription strand), `SECOND_READ_TRANSCRIPTION_STRAND` (stranded, second read strand is the transcriptioin strand) and `NONE` (unstranded). Pinging @akahles, our RNA-Seq expert, here for his input.

**Comment by akahles** [comment]
Hi @junjun-zhang ,  I agree that the nomenclature around strandedness in RNA-Seq is a bit confusing. Classically, we used the TopHat nomenclature (fr-firststrand, fr-secondstrand, fr unstranded), but I see that this can be quite confusing. Regarding the Picard nomenclature, I think this is more clear, but I don't really like the use of "transcription strand", as this not a common name of one of the two strands (forward/reverse, coding/template, 5'->3'/3'->5', ...) and hence could lead to misinterpretation. I would like something like, `FIRST_READ_FORWARD_STRAND` or `FIRST_READ_CODING_STRAND`. On the other hand, I see that you don't want to introduce another naming convention. In that case, I'd probably choose Salmon, as the most versatile framework to express protocols.

**Comment by junjun-zhang** [comment]
Thanks for sharing your thoughts @akahles. I am actually open to introducing new naming conventions if none of the existing ones fits well. You are right, `transcription strand` is unclear and not a common term. Then let's just fix that by using sense/antisense strand instead. How about `FIRST_READ_SENSE_STRAND`, `SECOND_READ_SENSE_STRAND`, and `UNSTRANDED` as acceptable terms?  For practical reasons, we could also add `UNKNOWN` if strandedness is indeed unknown.

Regarding Salmon terms, although it's the most versitile I am a bit afriad it's overcomplicated (unnecessarily). As long as we captured the critical information about strandedness, ie, library is stranded or not, what's the orientation of the first read, other information provided by Salmon, ie, inward/outward/matching can be easily inferred from looking at the read mapping result. Which is probably why many other tools do not include such information as part of their strandedness.

**Comment by lindaxiang** [comment]
@junjun-zhang @akahles thanks for providing your opinions. 
Can I suggest to remove `UNKNOWN` from the enum of `library_strandedness`? Now `library_strandedness` is a required field for down streaming tool `picard-collect-rna-seq-metrics`, if we allow `UNKNOWN`, we will have to use additional tool to infer it.

**Comment by junjun-zhang** [comment]
Sure, I only suggested `UNKNOWN` in case it's needed. It's ok without it if we don't end up forcing users to pick up something arbitrary when library strandedness is indeed unknown to them.

**Review by junjun-zhang — APPROVED** [review]
looking good

**Comment by lindaxiang** [comment]
@junjun-zhang @akahles The nomenclature around strandedness in RNA-Seq is indeed confusing. 
Just want to make sure I understand it correctly. 
Are the mappings in the table looking correct to you?

ARGO|PICARD|HISAT2|STAR
:-----:|:-----:|:-----:|:-----:
FIRST\_READ\_SENSE\_STRAND|FIRST\_READ\_TRANSCRIPTION\_STRAND|F/FR|n/a (STAR doesn’t use library strandedness info for mapping)
FIRST\_READ\_ANTISENSE\_STRAND|SECOND\_READ\_TRANSCRIPTION\_STRAND|R/RF|n/a
UNSTRANDED|NONE|NONE|n/a

**Comment by akahles** [comment]
Table looks good to me.

**Review by junjun-zhang — APPROVED** [review]

**Pull request merged**
